= Wirtschaft und Recht
Thomas Spindler
1.0.0, {docdate}: WRRE
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:stylesheet: ../css/dark.css

== Einführung

eine schriftliche Leistungsüberprüfung im Schuljahr, wahrscheinlich Dezember

Termin: 01.12.2022

Verschieben möglich, wenn dies benötigt wird

Teile der Noten:

* Test
* Mitarbeit
* Dauerhausübung

=== Dauerhausübung:

Aktuell halten, vor allem was in der Welt passiert, aus Qualitätsmedien

IMPORTANT: Jeden Montag wird gefragt, was wir gelesen haben.

Was wir hierbei nicht mitnehmen:

* Kronenzeitung
* Schnell-pop-up news
* Nachrichten ohne Erklärung

Was wir hierbei nehmen:

* Die Presse
* Die Zeit
* Valter
* Kurier
* OÖ Nachrichten (etwas aufpassen)
* Der Spiegel (ist allerdings deutsches Recht)

== Rechtsformen

== Privates und öffentliches Recht

=== privates Recht:

* Bürger gegen Bürger
* Kaufvertrag

=== öffentliches Recht

z.B.: Standesbeamter bei Hochzeit
Bürger gegen Staat

=== Zwingendes Recht und nachgiebiges Recht

Zwingendes Recht muss befolgt werden

nachgiebiges Recht kann ausgemacht oder abgesprochen werden.

== Rechtsnormen

Österreich ist:

* Rechtsstaat
* Gewaltenteilend

* Verordnung: Gilt sofort für alle (DSGVO) +
* Richtlinie: muss zuerst in nationales Recht umgewandelt werden (z.B Anti - Diskriminierung)
* Verfassungsrecht: hat einen sehr hohen stellen

== ErwachsenenRegelung oder so

* Vorsorgevollmacht
* Gewählter Erwachsenenvertreter

== Verträge

Verträge werden andauern abgeschlossen

=== Werkvertrag

Ein Erfolg, den man verspricht

=== Kaufvertrag

wird abgeschlossen, immer wenn jemand etwas kauft


=== Garantie

Kann beim Produkt dabei sein, kann aber auch als extra geld und / oder als Extrapacket (mit extra kosten) erhalten werden


==== Garantiefall

* Primär Beihilfe:
** Austausch
**  Reperatur

Dies darf allerdings der Kunde entscheiden

* Sekundärbeihilfe
** Behalten bei teilweiser Rückerstattung
** Komplette Rückerstattung (gegen Geld)

IMPORTANT: Bei gebrauchter Wahre: Kann auf 1 Jahr verringert werden

Die Reperatur muss in einem angemessenen Zeitraum passieren, es soll auf in gewissen Fällen ein Ersatzgerät bereitgestellt werden.

=== Gewährleistung

z.B Bein einem Auto, dass 200 km/h schaffen sollte, allerdings nur 180 erreicht.

Ist vom verschulden unabhängig

Wenn ich irgendwas allerdings deutlich sehe, ich diese Ware allerdings trotzdem kaufe, fällt die Gewährleistung aus.

Bei Abnutzung gibt es keine Gewährleistung

=== Beweislast

Im 1. Jahr beim Händler, danach beim Kunden

